name: Daily AQI Update

on:
  schedule:
    # 10:00 AM IST
    - cron: '30 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      # ---------------- CHECKOUT ----------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # ---------------- PYTHON SETUP ----------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # ---------------- INSTALL DEPENDENCIES ----------------
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip

          pip install pandas
          pip install numpy
          pip install requests
          pip install statsmodels
          pip install prophet
          pip install river
          pip install plotly
          pip install streamlit

      # ---------------- RUN PIPELINE ----------------
      - name: Run Processing Script
        env:
          WAQI_TOKEN: ${{ secrets.WAQI_TOKEN }}
        run: python daily_runner.py

      # ---------------- COMMIT OUTPUT FILES ----------------
      - name: Commit Results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto: Update AQI data, Forecast, Drift Logs"
          file_pattern: "*.csv"
